class Gifts {
  final List<String> giftsImagePath = [
    "1F94A_BoxingGlove_MOD_01_01 1.png",
    "blue medical gloves.png",
    "coffee spilling out of mug.png",
    "cupcake with cherry.png",
    "easter egg.png",
    "front view of black eyeglasses.png",
    "front view of red scooter.png",
    "image 27.png",
    "snow globe with house and trees.png",
    "soccer ball.png",
    "tool box.png",
    "t-shirt mockup.png",
    "White skin hands with a phone.png",
    "white sneakers.png",
    "Wrapped gift.png",
  ];
  final List<String> giftsName = [
    "test",
    "blue test",
    "coffee ",
    "cupcake test",
    "test",
    "front test",
    "front ",
    "test",
    "snow ",
    "test",
    "test",
    "t-test",
    "White ",
    "test",
    "test",
  ];
  final List<int> giftsPrices = [
    26,
    25,
    21,
    22,
    25,
    24,
    22,
    22,
    21,
    21,
    20,
    21,
    21,
    22,
    29,
  ];
}
